
// This file has been generated by genreflex with the --capabilities option
static  const char* clnames[] = {
//--Begin classes
  "LCGReflex/HiggsGenEvent",
  "LCGReflex/JetProperties",
  "LCGReflex/GenZDecayProperties",
  "LCGReflex/std::vector<GenZDecayProperties>",
  "LCGReflex/std::vector<JetProperties>",
  "LCGReflex/edm::Wrapper<std::vector<GenZDecayProperties> >",
  "LCGReflex/edm::Wrapper<GenZDecayProperties>",
  "LCGReflex/edm::Wrapper<std::vector<JetProperties> >",
  "LCGReflex/edm::Wrapper<JetProperties>",
  "LCGReflex/edm::Wrapper<HiggsGenEvent>",
  "LCGReflex/edm::RefProd<GenZDecayProperties>",
  "LCGReflex/edm::RefProd<JetProperties>",
  "LCGReflex/edm::RefProd<HiggsGenEvent>",
//--End   classes
//--Final End
};

extern "C" void SEAL_CAPABILITIES (const char**& names, int& n )
{ 
  names = clnames;
  n = sizeof(clnames)/sizeof(char*);
}

