
// This file has been generated by genreflex with the --capabilities option
static  const char* clnames[] = {
//--Begin classes
  "LCGReflex/TtSemiEvtSolution",
  "LCGReflex/TtFullHadronicEvent",
  "LCGReflex/TtSemiLeptonicEvent",
  "LCGReflex/StEvtSolution",
  "LCGReflex/TtHadEvtSolution",
  "LCGReflex/TtGenEvent",
  "LCGReflex/TtDilepEvtSolution",
  "LCGReflex/TopGenEvent",
  "LCGReflex/StGenEvent",
  "LCGReflex/TtEvent",
  "LCGReflex/TtFullLeptonicEvent",
  "LCGReflex/std::pair<edm::RefToBase<reco::Jet>,reco::CATopJetProperties>",
  "LCGReflex/std::pair<reco::CompositeCandidate,std::vector<int> >",
  "LCGReflex/std::pair<WDecay::LeptonType,WDecay::LeptonType>",
  "LCGReflex/std::vector<StEvtSolution>",
  "LCGReflex/std::vector<TtHadEvtSolution>",
  "LCGReflex/std::vector<TtSemiEvtSolution>",
  "LCGReflex/std::vector<TtDilepEvtSolution>",
  "LCGReflex/std::vector<std::pair<reco::CompositeCandidate,std::vector<int> > >",
  "LCGReflex/std::map<TtEvent::HypoClassKey,std::vector<std::pair<reco::CompositeCandidate,std::vector<int> > > >",
  "LCGReflex/std::map<TtEvent::HypoClassKey,int>",
  "LCGReflex/edm::Wrapper<std::vector<StEvtSolution> >",
  "LCGReflex/edm::Wrapper<std::vector<TtHadEvtSolution> >",
  "LCGReflex/edm::Wrapper<std::vector<TtSemiEvtSolution> >",
  "LCGReflex/edm::Wrapper<std::vector<TtDilepEvtSolution> >",
  "LCGReflex/edm::Wrapper<std::vector<std::pair<reco::CompositeCandidate,std::vector<int> > > >",
  "LCGReflex/edm::Wrapper<reco::CompositeCandidate>",
  "LCGReflex/edm::Wrapper<TtFullHadronicEvent>",
  "LCGReflex/edm::Wrapper<TtSemiLeptonicEvent>",
  "LCGReflex/edm::Wrapper<TtFullLeptonicEvent>",
  "LCGReflex/edm::Wrapper<TopGenEvent>",
  "LCGReflex/edm::Wrapper<StGenEvent>",
  "LCGReflex/edm::Wrapper<TtGenEvent>",
  "LCGReflex/edm::RefProd<TtFullHadronicEvent>",
  "LCGReflex/edm::RefProd<TtSemiLeptonicEvent>",
  "LCGReflex/edm::RefProd<TtFullLeptonicEvent>",
  "LCGReflex/edm::RefProd<TopGenEvent>",
  "LCGReflex/edm::RefProd<StGenEvent>",
  "LCGReflex/edm::RefProd<TtGenEvent>",
  "LCGReflex/reco::CATopJetTagInfo",
  "LCGReflex/reco::CATopJetProperties",
  "LCGReflex/edm::RefVector<std::vector<reco::CATopJetTagInfo>,reco::CATopJetTagInfo,edm::refhelper::FindUsingAdvance<std::vector<reco::CATopJetTagInfo>,reco::CATopJetTagInfo> >",
  "LCGReflex/std::vector<reco::CATopJetTagInfo>",
  "LCGReflex/edm::RefProd<std::vector<reco::CATopJetTagInfo> >",
  "LCGReflex/edm::Ref<std::vector<reco::CATopJetTagInfo>,reco::CATopJetTagInfo,edm::refhelper::FindUsingAdvance<std::vector<reco::CATopJetTagInfo>,reco::CATopJetTagInfo> >",
  "LCGReflex/edm::Wrapper<std::vector<reco::CATopJetTagInfo> >",
  "LCGReflex/edm::reftobase::RefHolder<edm::Ref<std::vector<reco::CATopJetTagInfo>,reco::CATopJetTagInfo,edm::refhelper::FindUsingAdvance<std::vector<reco::CATopJetTagInfo>,reco::CATopJetTagInfo> > >",
  "LCGReflex/edm::reftobase::Holder<reco::BaseTagInfo,edm::Ref<std::vector<reco::CATopJetTagInfo>,reco::CATopJetTagInfo,edm::refhelper::FindUsingAdvance<std::vector<reco::CATopJetTagInfo>,reco::CATopJetTagInfo> > >",
//--End   classes
//--Final End
};

extern "C" void SEAL_CAPABILITIES (const char**& names, int& n )
{ 
  names = clnames;
  n = sizeof(clnames)/sizeof(char*);
}

