
// This file has been generated by genreflex with the --capabilities option
static  const char* clnames[] = {
//--Begin classes
  "LCGReflex/ResolutionVariables",
  "LCGReflex/std::vector<std::vector<int> >",
  "LCGReflex/edm::Association<edm::View<reco::Candidate> >",
  "LCGReflex/edm::Wrapper<edm::Association<edm::View<reco::Candidate> > >",
  "LCGReflex/edm::RefToBaseVector<pat::Jet>",
  "LCGReflex/edm::Wrapper<edm::RefToBaseVector<pat::Jet> >",
  "LCGReflex/edm::RefToBaseVector<pat::Muon>",
  "LCGReflex/edm::Wrapper<edm::RefToBaseVector<pat::Muon> >",
  "LCGReflex/edm::Wrapper<std::vector<std::vector<int> > >",
  "LCGReflex/edm::RefProd<edm::View<reco::Candidate> >",
  "LCGReflex/edm::reftobase::BaseVectorHolder<pat::Jet>",
  "LCGReflex/edm::reftobase::BaseVectorHolder<pat::Muon>",
//--End   classes
//--Final End
};

extern "C" void SEAL_CAPABILITIES (const char**& names, int& n )
{ 
  names = clnames;
  n = sizeof(clnames)/sizeof(char*);
}

