
// This file has been generated by genreflex with the --capabilities option
static  const char* clnames[] = {
//--Begin classes
  "LCGReflex/std::pair<TString,std::vector<double> >",
  "LCGReflex/ztop::JetCorrectorParametersCollection",
  "LCGReflex/std::vector<ztop::JetCorrectorParametersCollection>",
  "LCGReflex/ztop::JetCorrectorParameters",
  "LCGReflex/ztop::JetCorrectorParameters::Record",
  "LCGReflex/std::vector<ztop::JetCorrectorParameters::Record>",
  "LCGReflex/std::vector<ztop::JetCorrectorParameters>",
  "LCGReflex/ztop::JERBase",
  "LCGReflex/std::vector<ztop::JERBase>",
  "LCGReflex/ztop::JECBase",
  "LCGReflex/std::vector<ztop::JECBase>",
  "LCGReflex/ztop::bTagBase",
  "LCGReflex/std::vector<ztop::bTagBase>",
  "LCGReflex/std::vector<TH2D>",
  "LCGReflex/std::vector<long>",
  "LCGReflex/std::vector<std::pair<TString,std::vector<double> > >",
  "LCGReflex/std::vector<double>",
  "LCGReflex/std::vector<TString>",
  "LCGReflex/std::map<std::basic_string<char>,std::vector<TH2D> >",
  "LCGReflex/std::map<TString,std::vector<TH2D> >",
  "LCGReflex/ztop::JetCorrectionUncertainty",
  "LCGReflex/ztop::SimpleJetCorrectionUncertainty",
  "LCGReflex/ztop::JetCorrectorParameters::Definitions",
  "LCGReflex/std::pair<int,ztop::JetCorrectorParameters>",
  "LCGReflex/std::vector<std::pair<int,ztop::JetCorrectorParameters> >",
//--End   classes
//--Final End
};

extern "C" void SEAL_CAPABILITIES (const char**& names, int& n )
{ 
  names = clnames;
  n = sizeof(clnames)/sizeof(char*);
}

